all: aa ma nq lq slq 
aa: aa2.cmd aa3.cmd aa4.cmd aa6.cmd aa8.cmd aa12.cmd aa16.cmd aa24.cmd aa32.cmd aa48.cmd aa64.cmd
ma: ma2.cmd ma3.cmd ma4.cmd ma5.cmd ma6.cmd ma7.cmd ma8.cmd ma9.cmd ma10.cmd ma12.cmd
nq: nq5.cmd nq6.cmd nq8.cmd nq10.cmd nq12.cmd nq13.cmd nq14.cmd nq15.cmd nq16.cmd
lq: lq4.cmd lq8.cmd lq9.cmd lq10.cmd lq11.cmd lq12.cmd lq13.cmd lq14.cmd lq15.cmd lq16.cmd
slq: slq4.cmd slq8.cmd slq9.cmd slq10.cmd slq11.cmd slq12.cmd slq13.cmd slq14.cmd slq15.cmd slq16.cmd
sliq: sliq4.cmd sliq8.cmd sliq9.cmd sliq10.cmd sliq11.cmd sliq12.cmd sliq13.cmd sliq14.cmd sliq15.cmd sliq16.cmd
slsq: slsq4.cmd slsq8.cmd slsq9.cmd slsq10.cmd slsq11.cmd slsq12.cmd slsq13.cmd slsq14.cmd slsq15.cmd slsq16.cmd

aa2.cmd: circuit.py addassoc.py
	./addassoc.py 2 > aa2.cmd

aa3.cmd: circuit.py addassoc.py
	./addassoc.py 3 > aa3.cmd

aa4.cmd: circuit.py addassoc.py
	./addassoc.py 4 > aa4.cmd

aa6.cmd: circuit.py addassoc.py
	./addassoc.py 6 > aa6.cmd

aa8.cmd: circuit.py addassoc.py
	./addassoc.py 8 > aa8.cmd

aa12.cmd: circuit.py addassoc.py
	./addassoc.py 12 > aa12.cmd

aa16.cmd: circuit.py addassoc.py
	./addassoc.py 16 > aa16.cmd

aa24.cmd: circuit.py addassoc.py
	./addassoc.py 24 > aa24.cmd

aa32.cmd: circuit.py addassoc.py
	./addassoc.py 32 > aa32.cmd

aa48.cmd: circuit.py addassoc.py
	./addassoc.py 48 > aa48.cmd

aa64.cmd: circuit.py addassoc.py
	./addassoc.py 64 > aa64.cmd

ma2.cmd: circuit.py multassoc.py
	./multassoc.py 2 > ma2.cmd

ma3.cmd: circuit.py multassoc.py
	./multassoc.py 3 > ma3.cmd

ma4.cmd: circuit.py multassoc.py
	./multassoc.py 4 > ma4.cmd

ma5.cmd: circuit.py multassoc.py
	./multassoc.py 5 > ma5.cmd

ma6.cmd: circuit.py multassoc.py
	./multassoc.py 6 > ma6.cmd

ma7.cmd: circuit.py multassoc.py
	./multassoc.py 7 > ma7.cmd

ma8.cmd: circuit.py multassoc.py
	./multassoc.py 8 > ma8.cmd

ma9.cmd: circuit.py multassoc.py
	./multassoc.py 9 > ma9.cmd

ma10.cmd: circuit.py multassoc.py
	./multassoc.py 10 > ma10.cmd

ma12.cmd: circuit.py multassoc.py
	./multassoc.py 12 > ma12.cmd

ma16.cmd: circuit.py multassoc.py
	./multassoc.py 16 > ma16.cmd

nq5.cmd: circuit.py nqueen.py
	./nqueen.py 5 > nq5.cmd

nq6.cmd: circuit.py nqueen.py
	./nqueen.py 6 > nq6.cmd

nq7.cmd: circuit.py nqueen.py
	./nqueen.py 7 > nq7.cmd

nq8.cmd: circuit.py nqueen.py
	./nqueen.py 8 > nq8.cmd

nq10.cmd: circuit.py nqueen.py
	./nqueen.py 10 > nq10.cmd

nq12.cmd: circuit.py nqueen.py
	./nqueen.py 12 > nq12.cmd

nq13.cmd: circuit.py nqueen.py
	./nqueen.py 13 > nq13.cmd

nq14.cmd: circuit.py nqueen.py
	./nqueen.py 14 > nq14.cmd

nq15.cmd: circuit.py nqueen.py
	./nqueen.py 15 > nq15.cmd

nq16.cmd: circuit.py nqueen.py
	./nqueen.py 16 > nq16.cmd

lq4.cmd: circuit.py lqueen.py
	./lqueen.py 4 > lq4.cmd

lq8.cmd: circuit.py lqueen.py
	./lqueen.py 8 > lq8.cmd

lq9.cmd: circuit.py lqueen.py
	./lqueen.py 9 > lq9.cmd

lq10.cmd: circuit.py lqueen.py
	./lqueen.py 10 > lq10.cmd

lq11.cmd: circuit.py lqueen.py
	./lqueen.py 11 > lq11.cmd

lq12.cmd: circuit.py lqueen.py
	./lqueen.py 12 > lq12.cmd

lq13.cmd: circuit.py lqueen.py
	./lqueen.py 13 > lq13.cmd

lq14.cmd: circuit.py lqueen.py
	./lqueen.py 14 > lq14.cmd

lq15.cmd: circuit.py lqueen.py
	./lqueen.py 15 > lq15.cmd

lq16.cmd: circuit.py lqueen.py
	./lqueen.py 16 > lq16.cmd

slq4.cmd: circuit.py slqueen.py
	./slqueen.py 4 > slq4.cmd

slq8.cmd: circuit.py slqueen.py
	./slqueen.py 8 > slq8.cmd

slq9.cmd: circuit.py slqueen.py
	./slqueen.py 9 > slq9.cmd

slq10.cmd: circuit.py slqueen.py
	./slqueen.py 10 > slq10.cmd

slq11.cmd: circuit.py slqueen.py
	./slqueen.py 11 > slq11.cmd

slq12.cmd: circuit.py slqueen.py
	./slqueen.py 12 > slq12.cmd

slq13.cmd: circuit.py slqueen.py
	./slqueen.py 13 > slq13.cmd

slq14.cmd: circuit.py slqueen.py
	./slqueen.py 14 > slq14.cmd

slq15.cmd: circuit.py slqueen.py
	./slqueen.py 15 > slq15.cmd

slq16.cmd: circuit.py slqueen.py
	./slqueen.py 16 > slq16.cmd

sliq4.cmd: circuit.py sliqueen.py
	./sliqueen.py 4 > sliq4.cmd

sliq8.cmd: circuit.py sliqueen.py
	./sliqueen.py 8 > sliq8.cmd

sliq9.cmd: circuit.py sliqueen.py
	./sliqueen.py 9 > sliq9.cmd

sliq10.cmd: circuit.py sliqueen.py
	./sliqueen.py 10 > sliq10.cmd

sliq11.cmd: circuit.py sliqueen.py
	./sliqueen.py 11 > sliq11.cmd

sliq12.cmd: circuit.py sliqueen.py
	./sliqueen.py 12 > sliq12.cmd

sliq13.cmd: circuit.py sliqueen.py
	./sliqueen.py 13 > sliq13.cmd

sliq14.cmd: circuit.py sliqueen.py
	./sliqueen.py 14 > sliq14.cmd

sliq15.cmd: circuit.py sliqueen.py
	./sliqueen.py 15 > sliq15.cmd

sliq16.cmd: circuit.py sliqueen.py
	./sliqueen.py 16 > sliq16.cmd

slsq4.cmd: circuit.py slsqueen.py
	./slsqueen.py 4 > slsq4.cmd

slsq8.cmd: circuit.py slsqueen.py
	./slsqueen.py 8 > slsq8.cmd

slsq9.cmd: circuit.py slsqueen.py
	./slsqueen.py 9 > slsq9.cmd

slsq10.cmd: circuit.py slsqueen.py
	./slsqueen.py 10 > slsq10.cmd

slsq11.cmd: circuit.py slsqueen.py
	./slsqueen.py 11 > slsq11.cmd

slsq12.cmd: circuit.py slsqueen.py
	./slsqueen.py 12 > slsq12.cmd

slsq13.cmd: circuit.py slsqueen.py
	./slsqueen.py 13 > slsq13.cmd

slsq14.cmd: circuit.py slsqueen.py
	./slsqueen.py 14 > slsq14.cmd

slsq15.cmd: circuit.py slsqueen.py
	./slsqueen.py 15 > slsq15.cmd

slsq16.cmd: circuit.py slsqueen.py
	./slsqueen.py 16 > slsq16.cmd


clean:
	rm -f *.pyc *~ *.cmd


