all: aa ma nq
aa: aa2.cmd aa3.cmd aa4.cmd aa6.cmd aa8.cmd aa12.cmd aa16.cmd aa24.cmd aa32.cmd aa48.cmd aa64.cmd
ma: ma2.cmd ma3.cmd ma4.cmd ma5.cmd ma6.cmd ma7.cmd ma8.cmd ma10.cmd ma12.cmd
nq: nq5.cmd nq6.cmd nq8.cmd nq10.cmd nq12.cmd nq13.cmd nq14.cmd nq15.cmd nq16.cmd


aa2.cmd: circuit.py addassoc.py
	./addassoc.py 2 > aa2.cmd

aa3.cmd: circuit.py addassoc.py
	./addassoc.py 3 > aa3.cmd

aa4.cmd: circuit.py addassoc.py
	./addassoc.py 4 > aa4.cmd

aa6.cmd: circuit.py addassoc.py
	./addassoc.py 6 > aa6.cmd

aa8.cmd: circuit.py addassoc.py
	./addassoc.py 8 > aa8.cmd

aa12.cmd: circuit.py addassoc.py
	./addassoc.py 12 > aa12.cmd

aa16.cmd: circuit.py addassoc.py
	./addassoc.py 16 > aa16.cmd

aa24.cmd: circuit.py addassoc.py
	./addassoc.py 24 > aa24.cmd

aa32.cmd: circuit.py addassoc.py
	./addassoc.py 32 > aa32.cmd

aa48.cmd: circuit.py addassoc.py
	./addassoc.py 48 > aa48.cmd

aa64.cmd: circuit.py addassoc.py
	./addassoc.py 64 > aa64.cmd

ma2.cmd: circuit.py multassoc.py
	./multassoc.py 2 > ma2.cmd

ma3.cmd: circuit.py multassoc.py
	./multassoc.py 3 > ma3.cmd

ma4.cmd: circuit.py multassoc.py
	./multassoc.py 4 > ma4.cmd

ma5.cmd: circuit.py multassoc.py
	./multassoc.py 5 > ma5.cmd

ma6.cmd: circuit.py multassoc.py
	./multassoc.py 6 > ma6.cmd

ma7.cmd: circuit.py multassoc.py
	./multassoc.py 7 > ma7.cmd

ma8.cmd: circuit.py multassoc.py
	./multassoc.py 8 > ma8.cmd

ma10.cmd: circuit.py multassoc.py
	./multassoc.py 10 > ma10.cmd

ma12.cmd: circuit.py multassoc.py
	./multassoc.py 12 > ma12.cmd

ma16.cmd: circuit.py multassoc.py
	./multassoc.py 16 > ma16.cmd

nq5.cmd: circuit.py nqueen.py
	./nqueen.py 5 > nq5.cmd

nq6.cmd: circuit.py nqueen.py
	./nqueen.py 6 > nq6.cmd

nq7.cmd: circuit.py nqueen.py
	./nqueen.py 7 > nq7.cmd

nq8.cmd: circuit.py nqueen.py
	./nqueen.py 8 > nq8.cmd

nq10.cmd: circuit.py nqueen.py
	./nqueen.py 10 > nq10.cmd

nq12.cmd: circuit.py nqueen.py
	./nqueen.py 12 > nq12.cmd

nq13.cmd: circuit.py nqueen.py
	./nqueen.py 13 > nq13.cmd

nq14.cmd: circuit.py nqueen.py
	./nqueen.py 14 > nq14.cmd

nq15.cmd: circuit.py nqueen.py
	./nqueen.py 15 > nq15.cmd

nq16.cmd: circuit.py nqueen.py
	./nqueen.py 16 > nq16.cmd

clean:
	rm -f *.pyc *~


